
{% set name = "STIR" %}
{% set version = "4.0.0.alpha" %}
{% set git_tag = "stir_rel_4_00_alpha" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/UCL/STIR.git
  git_rev: {{ git_tag }}
  git_depth: 1000 # (Defaults to -1/not shallow), has to be large enough such that the tag is actually in the last xxx commits

build:
  skip: true  # [py2k]
  skip: true  # [win and py<36]
  skip: true  # [win]
  skip: true  # [osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - boost-cpp
    - numpy
    - swig
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - stir
  source_files:
    - recon_test_pack
    - src/swig/test/python
  commands:
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}   # [osx]
    - pytest src/swig/test/python
    - cd recon_test_pack && ./run_tests.sh --nointbp  # [not win]
    - cd recon_test_pack  # [win]
    - run_tests  # [win]


about:
  home: http://stir.sourceforge.net/
  license: GPL and LGPL
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Software for Tomographic Image Reconstruction'
  description: |
    STIR is Open Source software for use in tomographic imaging.
    Its aim is to provide a Multi-Platform Object-Oriented framework for all data manipulations in tomographic imaging.
  doc_url: http://stir.sourceforge.net/documentation
  dev_url: https://github.com/UCL/STIR

extra:
  recipe-maintainers:
    - olivierverdier
    - KrisThielemans
    - paskino
    - casperdcl
