travis:
  secure:
    BINSTAR_TOKEN: aBs5kP7JRmKTLrNESighEK3+zA1b38srkvNPzqGBPZxo5/NQF+Wqn/I+MoqJvaRkyw1YjwwaA1g0PUqik+UX+qd688Hp3S8YzZ4/I8wQ8J0KBDFLnD5FmyIcYoEtZTr+oCaKWnfo1JoEV4y8aqVG320UGSNVKMvPBRoBmnyc0oHJUbmQd62AZF+ReUAuC8yuCXil0E4lKkn3Np81/B1oYzdX4wZhxF754IIMNCucNWVb6V5zo/s8dQHruaVVHhl6yR6tDp8020zFyfPCETRQk4lU1+oHGnfeze7zqksuAdJM2d1Vpijjg+z+oBWcgxzjmiX8LBZd98BVIcodLKIMyHzjdgKbasdpDofIHddFUZ7YY0Z7+7lD5eWvC67OlA/BN35cpNxH3C8QY+B+LBOQF92N5xflpzl/Xe7fznkMAkKTtWN39HTVWORcggK0eL6+Xcd/Ckqqea5N3xuDgrqERg9soG0KBCGoKQYGdFmbfIjiD9XOlArdG5pZYmklluzIE6ZnI5MIzKyvzevUmyAPUodACGvk7otxURNZOWuD9dMP9rnCQaCOd0JxXrtezlxajzyDlDU0ZbkuhmIF9zzB/pEacC856UGimMe63W3+CQzlT8cdzirUtGLKE0K5JARuvysvgC7m5wMjOuNetNJmRQn2kPq76VqcMtrEGbsW6U8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
